"""Sphinx configuration for FAT documentation."""

import os
import sys

# Path configuration
sys.path.insert(0, os.path.abspath('..'))

# Project information
project = 'FAT - Training Framework'
copyright = '2025'
author = 'Project Contributors'
version = '1.0.0'
release = '1.0.0'

# Extensions
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinx.ext.napoleon',
    'sphinx.ext.inheritance_diagram',
    'sphinx.ext.todo',
    'sphinxcontrib.mermaid',
    'myst_parser',
]

# MyST configuration
myst_fence_as_directive = ["mermaid"]

# Napoleon configuration (Google-style docstrings)
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Autodoc configuration
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'show-inheritance': True,
    'inherited-members': True,
    'special-members': '__init__',
    'undoc-members': True,
}

autodoc_typehints = 'description'
autodoc_typehints_description_target = 'documented'

# Mermaid configuration
mermaid_version = "11.0.0"
mermaid_init_js = """
    mermaid.initialize({
        startOnLoad: true,
        theme: 'default',
        securityLevel: 'loose',
        logLevel: 'info',
        flowchart: {
            useMaxWidth: true,
            htmlLabels: true,
        },
    });
"""

# Intersphinx configuration
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'torch': ('https://pytorch.org/docs/stable/', None),
}

# HTML theme
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
templates_path = ['_templates']

# Theme options
html_theme_options = {
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#2980B9',
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False,
}

# Output encoding
html_encoding = 'utf-8'

# Add any paths that contain custom static files (such as style sheets)
html_css_files = []

# The suffix(es) of source filenames
source_suffix = ['.md']

# The master toctree document
master_doc = 'index'

# The language for content autogenerated by Sphinx
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing
todo_include_todos = True

# Inheritance diagram configuration
inheritance_graph_attrs = {
    'rankdir': "TB",
    'size': '"6.0, 8.0"',
}
inheritance_node_attrs = {
    'shape': 'box',
    'fontsize': 10,
    'height': 0.50,
    'fontname': 'Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans',
}
inheritance_edge_attrs = {
    'fontsize': 10,
    'arrowsize': 0.5,
    'fontname': 'Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans',
}

# Keep track of file modifications for incremental builds
html_last_updated_fmt = '%b %d, %Y'

# Custom CSS adjustments for better diagram rendering
def setup(app):
    app.add_css_file('custom.css')
